{
  "name": "Alto Heumul",
  "difficulty": "Moderate",
  "distance": 5,
  "duration": 5,
  "country": "Chile",
  "description": "Trekking in Alto Heumul, Chile, offers an impressive experience in the middle of the wild nature of the region. Alto Heumul is a mountainous area located in southern Chile, known for its scenic beauty and challenging mountainous terrain.",
  "pointsOfInterest": "Glacier viewpoint, alpine lakes, Andean fauna"
} 


{
  "name": "Salto Angel Expedition",
  "difficulty": "Challenging",
  "distance": 60,
  "duration": 5,
  "country": "Venezuela",
  "description": "The Salto Angel Expedition is a challenging trekking route located in the Canaima National Park in Venezuela. It takes you on an adventurous journey to Angel Falls, the highest waterfall in the world. The trek includes hiking through dense rainforests, crossing rivers, and camping in the wilderness.",
  "pointsOfInterest": "Angel Falls, Auyán-Tepui, Canaima Lagoon, Kavac Cave"
}


{
  "name": "Quebrada de Macul",
  "difficulty": "Moderate",
  "distance": 8,
  "duration": 4,
  "country": "Chile",
  "description": "The Quebrada de Macul is a beautiful hiking trail located near Santiago, Chile. It offers a moderate level of difficulty and takes approximately 4 hours to complete. The trail takes you through a picturesque canyon with stunning views of the surrounding mountains and a refreshing river that runs through it. It's a great opportunity to immerse yourself in nature and enjoy the tranquility of the area.",
  "pointsOfInterest": "Canyon views, Mountain scenery, River crossing"
}


{
  "trekkingRoute": "649527cff98623f667156249",
  "comment": "Muy bueno el lugar"
}




//




_id
649527cff98623f667156249
name
"Alto Heumul: Laguna Fria"
difficulty
"Moderate"
distance
15
duration
5
country
"Chile"
description
"Trekking in Alto Heumul, Chile, offers an impressive experience in the…"
pointsOfInterest
"Glacier viewpoint, alpine lakes, Andean fauna"
createdAt
2023-06-23T05:04:15.045+00:00
__v
0